analytics: {}
color:
  brandColors:
    - '#A8A8A0'
    - '#782820'
    - '#989898'
    - '#904038'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.775086
  rhythmicContrast: 0.919808
  saturation: 0.826162
cta: {}
layout_spectrum: 0.05518
name: pixelwarpstudios.com
opengraph: {}
purpose: []
typography_spectrum: 0.494369
