name: pixelwarpstudios.com
favicon: null
layout_spectrum: 0.5831012513954192
typography_spectrum: 0.5831994926556945
title: Virtual Reality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494644'
    - '#000000'
    - '#f78508'
    - '#ffffff'
    - '#bebdbd'
  brandStrength: 0.3125
  lightness: 0.7750863870605826
  saturation: 0.8261620667763054
  rhythmicContrast: 0.9198083123192191
purpose: []
